name: iOS/Android

on:
  workflow_dispatch:
    inputs:
      platform:
        description: Platform to build for (all/android/ios)
        required: true
        default: all
      profile:
        description: EAS build profile (development/production)
        required: true
        default: production

jobs:
  build:
    name: Install and build
    runs-on: ubuntu-latest
    env:
      SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }} # Required for apps/with-sentry
    steps:
      - name: 🚀 Setup repo
        uses: actions/checkout@v3
      - name: 🚀 Setup Node
        uses: actions/setup-node@v3.5.1
        with:
          node-version: 16.x
      - name: 🚀 Setup EAS
        uses: expo/expo-github-action@v7
        with:
          eas-version: latest
          eas-cache: true
          token: ${{ secrets.EXPO_TOKEN }}
      - name: 🔎 Find cache
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: ♻️ Restore cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: 📋 Install dependencies
        run: YARN_ENABLE_IMMUTABLE_INSTALLS=false yarn install
      - name: 📢 Start EAS build
        run: eas build --non-interactive --wait --platform=${{ github.event.inputs.platform }} --profile=${{ github.event.inputs.profile }}
