/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * save, and this file will regenerate automatically.
 */

/**
 * WordPress credentials
 */
export interface WPCredentialsSchema {
  /**
   * Unique local identifier for the resource. Note: id is not unique for WP User IDs
   */
  localID?: string;
  id?: number;
  username?: string;
  first_name?: string;
  last_name?: string;
  email?: string;
  display_name?: string;
  nice_name?: string;
  last_access?: string;
  avatar_url?: string;
  jwt?: string;
  wp_nonce?: string;
  key_id?: number;
  key_permissions?: string;
  stores?: string[];
  [k: string]: any;
}
