/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * save, and this file will regenerate automatically.
 */

/**
 * WooCommerce Order Shipping Line schema
 */
export interface WooCommerceOrderShippingLineSchema {
  id?: number;
  /**
   * Shipping method name.
   */
  methodTitle?: string;
  /**
   * Shipping method ID.
   */
  methodId: string;
  /**
   * Shipping instance ID.
   */
  instanceId?: string;
  /**
   * Line total (after discounts).
   */
  total?: string;
  /**
   * Line total tax (after discounts).
   */
  totalTax?: string;
  /**
   * Line taxes.
   */
  taxes?: {
    /**
     * Tax rate ID.
     */
    id?: number;
    /**
     * Tax total.
     */
    total?: string;
    [k: string]: any;
  }[];
  /**
   * Meta data.
   */
  metaData?: {
    /**
     * Meta ID.
     */
    id?: number;
    /**
     * Meta key.
     */
    key?: string;
    /**
     * Meta value.
     */
    value?: string;
    [k: string]: any;
  }[];
  [k: string]: any;
}
