/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * save, and this file will regenerate automatically.
 */

/**
 * WooCommerce Product schema
 */
export interface WooCommerceProductSchema {
  /**
   * Unique local identifier for the resource.
   */
  uuid?: string;
  id?: number;
  name?: string;
  slug?: string;
  permalink?: string;
  date_created?: string;
  date_created_gmt?: string;
  date_modified?: string;
  date_modified_gmt?: string;
  type?: "simple" | "grouped" | "external" | "variable";
  status?: "draft" | "pending" | "private" | "publish";
  featured?: boolean;
  catalog_visibility?: string;
  description?: string;
  short_description?: string;
  sku?: string;
  price?: string;
  regular_price?: string;
  sale_price?: string;
  date_on_sale_from?: string;
  date_on_sale_from_gmt?: string;
  date_on_sale_to?: string;
  date_on_sale_to_gmt?: string;
  price_html?: string;
  on_sale?: boolean;
  purchasable?: boolean;
  total_sales?: number;
  virtual?: boolean;
  downloadable?: boolean;
  downloads?: any[];
  download_limit?: number;
  download_expiry?: number;
  external_url?: string;
  button_text?: string;
  tax_status?: "taxable" | "shipping" | "none";
  tax_class?: string;
  manage_stock?: boolean;
  stock_quantity?: number | null;
  stock_status?: "instock" | "outofstock" | "onbackorder";
  backorders?: "no" | "notify" | "yes";
  backorders_allowed?: boolean;
  backordered?: boolean;
  low_stock_amount?: number | null;
  sold_individually?: boolean;
  weight?: string;
  dimensions?: {
    length?: string;
    width?: string;
    height?: string;
    [k: string]: any;
  };
  shipping_required?: boolean;
  shipping_taxable?: boolean;
  shipping_class?: string;
  shipping_class_id?: number;
  reviews_allowed?: boolean;
  average_rating?: string;
  rating_count?: number;
  related_ids?: number[];
  upsell_ids?: number[];
  cross_sell_ids?: number[];
  parent_id?: number;
  purchase_note?: string;
  categories?: {
    id?: number;
    name?: string;
    slug?: string;
    [k: string]: any;
  }[];
  tags?: {
    id?: number;
    name?: string;
    slug?: string;
    [k: string]: any;
  }[];
  images?: {
    id?: number;
    date_created?: string;
    date_created_gmt?: string;
    date_modified?: string;
    date_modified_gmt?: string;
    src?: string;
    name?: string;
    alt?: string;
    [k: string]: any;
  }[];
  has_options?: boolean;
  attributes?: {
    id?: number;
    name?: string;
    position?: number;
    visible?: boolean;
    variation?: boolean;
    options?: string[];
    [k: string]: any;
  }[];
  default_attributes?: {
    id?: number;
    name?: string;
    option?: string;
    [k: string]: any;
  }[];
  variations?: string[];
  grouped_products?: number[];
  menu_order?: number;
  meta_data?: {
    id?: number;
    key?: string;
    value?: string;
    [k: string]: any;
  }[];
  links?: {
    collection?: {
      href?: string;
      [k: string]: any;
    }[];
    self?: {
      href?: string;
      [k: string]: any;
    }[];
    [k: string]: any;
  };
  thumbnail?: string;
  [k: string]: any;
}
