import './install-dom-parser';

import fs from 'node:fs/promises';
import path from 'node:path';

import { buildTemplateViewModel, type PaperWidth, type ReceiptFixture } from '../src/studio-core';
import { listBundledTemplates } from '../src/template-loader';
import { curatedSnapshotDir, fixturesDir, galleryTemplatesDir } from './studio-paths';

const checkMode = process.argv.includes('--check');
const updateMode = process.argv.includes('--update') || !checkMode;
const curatedTemplateIds = new Set(['standard-receipt', 'thermal-simple-80mm']);
const curatedFixtureIds = new Set(['gallery-default-receipt', 'long-product-names']);
const paperWidths: PaperWidth[] = ['80mm'];

async function readFixtures(): Promise<ReceiptFixture[]> {
	const files = (await fs.readdir(fixturesDir)).filter((file) => file.endsWith('.json')).sort();
	return Promise.all(
		files.map(async (file) => JSON.parse(await fs.readFile(path.join(fixturesDir, file), 'utf8')))
	);
}

function snapshotName(templateId: string, fixtureId: string, paperWidth: PaperWidth): string {
	return `${templateId}__${fixtureId}__${paperWidth}.json`;
}

async function main() {
	const [templates, fixtures] = await Promise.all([
		listBundledTemplates({ templatesDir: new URL(`file://${galleryTemplatesDir}/`) }),
		readFixtures(),
	]);
	const curatedTemplates = templates.filter((template) => curatedTemplateIds.has(template.id));
	const curatedFixtures = fixtures.filter((fixture) => curatedFixtureIds.has(fixture.id));
	if (curatedTemplates.length === 0 || curatedFixtures.length === 0) {
		throw new Error('No curated snapshot inputs found. Check gallery templates and fixtures.');
	}

	await fs.mkdir(curatedSnapshotDir, { recursive: true });
	const stale: string[] = [];
	const written: string[] = [];

	for (const template of curatedTemplates) {
		for (const fixture of curatedFixtures) {
			for (const paperWidth of paperWidths) {
				const model = buildTemplateViewModel({ template, fixture, paperWidth });
				const serialized = `${JSON.stringify(model, null, '\t')}\n`;
				const file = path.join(
					curatedSnapshotDir,
					snapshotName(template.id, fixture.id, paperWidth)
				);
				let current = '';
				try {
					current = await fs.readFile(file, 'utf8');
				} catch {
					/* new snapshot */
				}
				if (current !== serialized) {
					if (checkMode && !updateMode) stale.push(path.relative(process.cwd(), file));
					else {
						await fs.writeFile(file, serialized);
						written.push(path.relative(process.cwd(), file));
					}
				}
			}
		}
	}

	const summary = [
		`# Template Studio snapshot summary`,
		'',
		`Curated snapshots: ${curatedTemplates.length} templates × ${curatedFixtures.length} fixtures × ${paperWidths.length} widths.`,
		'Full-matrix drift reporting is intentionally not generated by this command.',
		'',
	].join('\n');
	const summaryFile = path.join(curatedSnapshotDir, 'README.md');
	let currentSummary = '';
	try {
		currentSummary = await fs.readFile(summaryFile, 'utf8');
	} catch {
		/* new summary */
	}
	if (currentSummary !== summary) {
		if (checkMode && !updateMode) stale.push(path.relative(process.cwd(), summaryFile));
		else {
			await fs.writeFile(summaryFile, summary);
			written.push(path.relative(process.cwd(), summaryFile));
		}
	}

	if (stale.length > 0) {
		throw new Error(
			`Curated snapshots are stale:\n${stale.join('\n')}\nRun pnpm test:snapshots -- --update to refresh.`
		);
	}
	console.log(
		written.length > 0
			? `Updated ${written.length} curated snapshots.`
			: 'Curated snapshots are current.'
	);
}

main().catch((error) => {
	console.error(error instanceof Error ? error.message : error);
	process.exitCode = 1;
});
