import type { PaymentMethodDescriptor, PaymentRow } from '@wcpos/order-math';
export const method: PaymentMethodDescriptor = {
	schema: 1,
	id: 'device',
	title: 'Reader',
	kind: 'card',
	pos_enabled: true,
	order: 1,
	capture: {
		mode: 'device',
		provider: 'simulated',
		hardware: {
			discovery: 'sdk',
			transports: [
				{ transport: 'bluetooth', offline: 'queue', tips: 'on_reader' },
				{ transport: 'tap_to_pay', offline: 'none', tips: 'none' },
			],
		},
		webview_available: false,
	},
	capabilities: {
		amount: { partial: true },
		change: false,
		refunds: { via: 'none', partial: false },
		tips: 'on_reader',
		offline: 'queue',
		void: true,
	},
	defaults: { order_status: 'completed', rounding: null, open_drawer: false },
	provider_data: {},
};
export const row: PaymentRow = {
	id: 'leg',
	source: 'app',
	order_id: 42,
	method_id: 'device',
	provider: 'simulated',
	kind: 'card',
	capture_mode: 'device',
	transport: 'bluetooth',
	recorded_offline: false,
	amount: '10.00',
	currency: 'USD',
	tendered: null,
	change: null,
	tip: null,
	status: 'pending',
	failure_reason: null,
	refunded_amount: '0.00',
	refunds: [],
	provider_refs: {},
	receipt: {},
	cashier_id: 1,
	store_id: 1,
	created_at_gmt: '2026-01-01T00:00:00Z',
	captured_at_gmt: null,
	updated_at_gmt: '2026-01-01T00:00:00Z',
};
