/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * save, and this file will regenerate automatically.
 */

/**
 * WooCommerce POS Store
 */
export interface WCPOSStoreSchema {
  /**
   * Unique local identifier for the resource.
   */
  _id?: string;
  id?: number;
  name?: string;
  accounting?: {
    currency?: {
      decimal?: string;
      format?: {
        neg?: string;
        pos?: string;
        zero?: string;
        [k: string]: any;
      };
      precision?: number;
      symbol?: string;
      thousand?: string;
      [k: string]: any;
    };
    number?: {
      decimal?: string;
      precision?: number;
      thousand?: string;
      [k: string]: any;
    };
    [k: string]: any;
  };
  [k: string]: any;
}
