/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * save, and this file will regenerate automatically.
 */

/**
 * WooCommerce POS Store
 */
export interface WCPOSStoreSchema {
  id?: number;
  name?: string;
  [k: string]: any;
}
