/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * save, and this file will regenerate automatically.
 */

/**
 * Global app user - different to WordPress user
 */
export interface UserSchema {
  id?: string;
  first_name?: string;
  last_name?: string;
  display_name?: string;
  sites?: {
    url?: string;
    name?: string;
    description?: string;
    home?: string;
    gmt_offset?: string;
    timezone_string?: string;
    wp_api_url?: string;
    wc_api_url?: string;
    wc_api_auth_url?: string;
    wp_credentials?: {
      id?: number;
      username?: string;
      first_name?: string;
      last_name?: string;
      email?: string;
      display_name?: string;
      last_access?: string;
      consumer_key?: string;
      consumer_secret?: string;
      key_id?: number;
      key_permissions?: string;
      stores?: {
        id?: number;
        name?: string;
        db_id?: string;
        uis?: {
          section?: string;
          sortBy?: string;
          sortDirection?: string;
          width?: string;
          columns?: {
            key?: string;
            order?: number;
            hide?: boolean;
            disableSort?: boolean;
            flexGrow?: number;
            flexShrink?: number;
            width?: string;
            [k: string]: any;
          }[];
          display?: {
            key?: string;
            order?: number;
            hide?: boolean;
            [k: string]: any;
          }[];
          [k: string]: any;
        }[];
        [k: string]: any;
      }[];
      [k: string]: any;
    }[];
    [k: string]: any;
  }[];
  [k: string]: any;
}
