/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * save, and this file will regenerate automatically.
 */

/**
 * WooCommerce Customer schema
 */
export interface WooCommerceCustomerSchema {
  /**
   * Unique identifier for the resource.
   */
  id?: string;
  /**
   * The email address for the customer.
   */
  email?: string;
  /**
   * Customer first name.
   */
  first_name?: string;
  /**
   * Customer last name.
   */
  last_name?: string;
  /**
   * Customer login name.
   */
  username?: string;
  /**
   * Customer password.
   */
  password?: string;
  /**
   * List of billing address data.
   */
  billing?: {
    [k: string]: any;
  };
  /**
   * List of shipping address data.
   */
  shipping?: {
    [k: string]: any;
  };
  /**
   * Meta data.
   */
  meta_data?: {
    /**
     * Meta ID.
     */
    id?: number;
    /**
     * Meta key.
     */
    key?: string;
    /**
     * Meta value.
     */
    value?: string;
    [k: string]: any;
  }[];
  [k: string]: any;
}
