/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * save, and this file will regenerate automatically.
 */

/**
 * WooCommerce Order Fee Line schema
 */
export interface WooCommerceOrderFeeLineSchema {
  /**
   * Unique local identifier for the resource.
   */
  localID?: string;
  id?: number;
  /**
   * Fee name.
   */
  name?: string;
  /**
   * Fee amount.
   */
  amount?: string;
  /**
   * Tax class of fee.
   */
  tax_class?: string;
  /**
   * Tax status of fee.
   */
  tax_status?: "taxable" | "none";
  /**
   * Line total (after discounts).
   */
  total?: string;
  /**
   * Line total tax (after discounts).
   */
  total_tax?: string;
  /**
   * Line taxes.
   */
  taxes?: {
    /**
     * Tax rate ID.
     */
    id?: number;
    /**
     * Tax total.
     */
    total?: string;
    /**
     * Tax subtotal.
     */
    subtotal?: string;
    [k: string]: any;
  }[];
  /**
   * Meta data.
   */
  meta_data?: {
    /**
     * Meta ID.
     */
    id?: number;
    /**
     * Meta key.
     */
    key?: string;
    /**
     * Meta value.
     */
    value?: string;
    [k: string]: any;
  }[];
  [k: string]: any;
}
