type Schema = import('@nozbe/watermelondb/Schema').TableSchemaSpec;

const schema: Schema = {
	name: 'orders',
	columns: [
		{ name: 'remote_id', type: 'number', isIndexed: true },
		{ name: 'parent_id', type: 'number' },
		{ name: 'number', type: 'string' },
		{ name: 'order_key', type: 'string' },
		{ name: 'created_via', type: 'string' },
		{ name: 'version', type: 'string' },
		{ name: 'status', type: 'string' },
		{ name: 'currency', type: 'string' },
		{ name: 'date_created', type: 'string' },
		{ name: 'date_created_gmt', type: 'string' },
		{ name: 'date_modified', type: 'string' },
		{ name: 'date_modified_gmt', type: 'string' },
		{ name: 'discount_total', type: 'string' },
		{ name: 'discount_tax', type: 'string' },
		{ name: 'shipping_total', type: 'string' },
		{ name: 'shipping_tax', type: 'string' },
		{ name: 'cart_tax', type: 'string' },
		{ name: 'total', type: 'string' },
		{ name: 'total_tax', type: 'string' },
		{ name: 'prices_include_tax', type: 'boolean' },
		{ name: 'customer_id', type: 'number' },
		{ name: 'customer_ip_address', type: 'string' },
		{ name: 'customer_user_agent', type: 'string' },
		{ name: 'customer_note', type: 'string' },
		{ name: 'billing', type: 'string' },
		{ name: 'shipping', type: 'string' },
		{ name: 'payment_method', type: 'string' },
		{ name: 'payment_method_title', type: 'string' },
		{ name: 'transaction_id', type: 'string' },
		{ name: 'date_paid', type: 'string' },
		{ name: 'date_paid_gmt', type: 'string' },
		{ name: 'date_completed', type: 'string', isOptional: true },
		{ name: 'date_completed_gmt', type: 'string', isOptional: true },
		{ name: 'cart_hash', type: 'string' },
		{ name: 'meta_data', type: 'string' },
		// { name: 'line_items', type: 'string' },
		{ name: 'tax_lines', type: 'string' },
		{ name: 'shipping_lines', type: 'string' },
		{ name: 'fee_lines', type: 'string' },
		{ name: 'coupon_lines', type: 'string' },
		{ name: 'refunds', type: 'string' },
	],
};

export default schema;
