type Schema = import('@nozbe/watermelondb/Schema').TableSchemaSpec;

const schema: Schema = {
	name: 'product_variations',
	columns: [
		{ name: 'remote_id', type: 'number', isIndexed: true },
		{ name: 'parent_id', type: 'string', isIndexed: true },
		{ name: 'date_created', type: 'string' },
		{ name: 'date_created_gmt', type: 'string' },
		{ name: 'date_modified', type: 'string' },
		{ name: 'date_modified_gmt', type: 'string' },
		{ name: 'description', type: 'string' },
		{ name: 'sku', type: 'string' },
		{ name: 'price', type: 'string' },
		{ name: 'regular_price', type: 'string' },
		{ name: 'sale_price', type: 'string' },
		{ name: 'date_on_sale_from', type: 'string', isOptional: true },
		{ name: 'date_on_sale_from_gmt', type: 'string', isOptional: true },
		{ name: 'date_on_sale_to', type: 'string', isOptional: true },
		{ name: 'date_on_sale_to_gmt', type: 'string', isOptional: true },
		{ name: 'on_sale', type: 'boolean' },
		{ name: 'status', type: 'string' },
		{ name: 'purchasable', type: 'boolean' },
		{ name: 'virtual', type: 'boolean' },
		{ name: 'downloadable', type: 'boolean' },
		{ name: 'downloads', type: 'string' },
		{ name: 'download_limit', type: 'number' },
		{ name: 'download_expiry', type: 'number' },
		{ name: 'tax_status', type: 'string' },
		{ name: 'tax_class', type: 'string' },
		{ name: 'manage_stock', type: 'boolean' },
		{ name: 'stock_quantity', type: 'string', isOptional: true },
		{ name: 'stock_status', type: 'string' },
		{ name: 'backorders', type: 'string' },
		{ name: 'backorders_allowed', type: 'boolean' },
		{ name: 'backordered', type: 'boolean' },
		{ name: 'weight', type: 'string' },
		{ name: 'dimensions', type: 'string' },
		{ name: 'shipping_taxable', type: 'boolean' },
		{ name: 'shipping_class', type: 'string' },
		{ name: 'shipping_class_id', type: 'number' },
		{ name: 'image', type: 'string' },
		{ name: 'attributes', type: 'string' },
		{ name: 'menu_order', type: 'number' },
		{ name: 'meta_data', type: 'string' },
		{ name: 'thumbnail', type: 'string' },
		{ name: 'barcode', type: 'string' },
	],
};

export default schema;
