import {
	addNumberPrecision,
	getRoundingPrecision,
	removeNumberPrecision,
	roundDiscount,
	roundHalfDown,
	roundHalfUp,
	roundTaxTotal,
} from './precision';

/**
 * PHP oracle values — generated by running the same inputs through PHP 8.5's
 * round() with PHP_ROUND_HALF_UP / PHP_ROUND_HALF_DOWN. These are the
 * ground-truth values that WooCommerce uses.
 *
 * To regenerate:
 *   php -r 'echo round(19.275, 2, PHP_ROUND_HALF_UP);'
 *
 * Key insight: PHP's round() determines direction from the number's shortest
 * decimal representation (same as JS `String(value)`). This means:
 *   - round(19.275, 2) = 19.28 (String is "19.275", digit at 3rd dp = 5 → up)
 *   - round(4.5 - 4.275, 2) = 0.22 (String is "0.22499...", 3rd dp = 4 → down)
 */
describe('precision utilities — PHP parity', () => {
	describe('roundHalfUp', () => {
		// [input, precision, expected PHP result]
		const cases: [number, number, number][] = [
			// Standard midpoints
			[0.225, 2, 0.23],
			[0.235, 2, 0.24],
			[0.245, 2, 0.25],
			[0.255, 2, 0.26],
			[2.725, 2, 2.73],
			[2.735, 2, 2.74],

			// Midpoints at larger magnitudes — these hit IEEE 754 representation
			// issues where value*100 lands just below .5. PHP still rounds up
			// because the shortest decimal representation has a 5 at the decision digit.
			[19.275, 2, 19.28],
			[19.285, 2, 19.29],
			[142.575, 2, 142.58],
			[45.225, 2, 45.23],

			// CRITICAL: float arithmetic results that are NOT true midpoints.
			// 4.5 - 4.275 = 0.22499999999999964 in IEEE 754 (not 0.225).
			// String representation is "0.22499999999999964" → 3rd dp = 4 → round DOWN.
			[4.5 - 4.275, 2, 0.22],
			// 2 - 1.33 = 0.6699999999999999 (not 0.67). Even though shifted*100 = 67
			// exactly, the string shows "0.6699999999999999" so we use floor(67+0.5)=67.
			[2 - 1.33, 2, 0.67],

			// Common tax amounts — non-midpoints
			[4.275, 2, 4.28],
			[3.267, 2, 3.27],
			[1.633, 2, 1.63],
			[1.634, 2, 1.63],

			// Non-midpoints (clear round direction)
			[1.234, 2, 1.23],
			[1.236, 2, 1.24],
			[0.001, 2, 0],
			[0.009, 2, 0.01],
			[0.004, 2, 0],
			[0.005, 2, 0.01],

			// Negative values — PHP ROUND_HALF_UP rounds away from zero
			[-0.225, 2, -0.23],
			[-19.275, 2, -19.28],
			[-2.725, 2, -2.73],

			// Zero decimal places
			[0.5, 0, 1],
			[1.5, 0, 2],
			[2.5, 0, 3],

			// Higher precision (3dp)
			[0.0225, 3, 0.023],
			[0.0235, 3, 0.024],
			[1.0005, 3, 1.001],
			[1.0015, 3, 1.002],

			// Large values
			[999.995, 2, 1000],
			[1000.005, 2, 1000.01],

			// Classic JS gotcha: 1.005 * 100 = 100.49999... but should round to 1.01
			[1.005, 2, 1.01],

			// 4dp precision
			[1.23456, 4, 1.2346],
		];

		it.each(cases)('roundHalfUp(%s, %i) = %s', (input, precision, expected) => {
			expect(roundHalfUp(input, precision)).toBe(expected);
		});

		it('returns 0 for 0', () => {
			expect(roundHalfUp(0, 2)).toBe(0);
		});

		it('returns value for integers', () => {
			expect(roundHalfUp(42, 2)).toBe(42);
		});

		it('handles Infinity', () => {
			expect(roundHalfUp(Infinity, 2)).toBe(Infinity);
			expect(roundHalfUp(-Infinity, 2)).toBe(-Infinity);
		});

		it('handles NaN', () => {
			expect(roundHalfUp(NaN, 2)).toBeNaN();
		});
	});

	describe('roundHalfDown', () => {
		// PHP ROUND_HALF_DOWN: at midpoint, round toward zero
		const cases: [number, number, number][] = [
			[0.225, 2, 0.22],
			[0.235, 2, 0.23],
			[0.245, 2, 0.24],
			[0.255, 2, 0.25],
			[2.725, 2, 2.72],
			[2.735, 2, 2.73],
			[19.275, 2, 19.27],
			[19.285, 2, 19.28],
			[142.575, 2, 142.57],
			[45.225, 2, 45.22],

			// Same float subtraction — also rounds down
			[4.5 - 4.275, 2, 0.22],

			// Non-midpoints (same result as HALF_UP)
			[1.234, 2, 1.23],
			[1.236, 2, 1.24],
			[4.275, 2, 4.27],
			[3.267, 2, 3.27],
			[1.633, 2, 1.63],

			// Negative — round toward zero (less negative)
			[-0.225, 2, -0.22],
			[-19.275, 2, -19.27],
			[-2.725, 2, -2.72],

			// Zero dp
			[0.5, 0, 0],
			[1.5, 0, 1],
			[2.5, 0, 2],
			[3.5, 0, 3],

			// 1.005 at midpoint → rounds DOWN to 1.0
			[1.005, 2, 1],

			// Large values
			[999.995, 2, 999.99],
			[1000.005, 2, 1000],
		];

		it.each(cases)('roundHalfDown(%s, %i) = %s', (input, precision, expected) => {
			expect(roundHalfDown(input, precision)).toBe(expected);
		});
	});

	describe('roundTaxTotal', () => {
		// WC: HALF_UP when prices exclude tax, HALF_DOWN when prices include tax.
		// This is the WC_TAX_ROUNDING_MODE constant.
		const cases: [number, number, boolean, number][] = [
			// Midpoints: direction depends on pricesIncludeTax
			[0.225, 2, false, 0.23],
			[0.225, 2, true, 0.22],
			[0.275, 2, false, 0.28],
			[0.275, 2, true, 0.27],
			[4.275, 2, false, 4.28],
			[4.275, 2, true, 4.27],
			[0.125, 2, false, 0.13],
			[0.125, 2, true, 0.12],
			[0.175, 2, false, 0.18],
			[0.175, 2, true, 0.17],
			[0.335, 2, false, 0.34],
			[0.335, 2, true, 0.33],

			// Non-midpoints: both modes agree
			[3.267, 2, false, 3.27],
			[3.267, 2, true, 3.27],
			[1.633, 2, false, 1.63],
			[1.633, 2, true, 1.63],
			[1.634, 2, false, 1.63],
			[1.634, 2, true, 1.63],

			// Float subtraction result (NOT midpoint)
			[4.5 - 4.275, 2, false, 0.22],
			[4.5 - 4.275, 2, true, 0.22],
		];

		it.each(cases)(
			'roundTaxTotal(%s, %i, pricesIncludeTax=%s) = %s',
			(input, dp, pricesIncludeTax, expected) => {
				expect(roundTaxTotal(input, dp, pricesIncludeTax)).toBe(expected);
			}
		);

		it('respects precision override', () => {
			expect(roundTaxTotal(2.5, 2, true, 0)).toBe(2);
			expect(roundTaxTotal(2.5, 2, false, 0)).toBe(3);
		});

		it('handles 0dp stores (JPY)', () => {
			expect(roundTaxTotal(2.5, 0, true)).toBe(2);
			expect(roundTaxTotal(2.5, 0, false)).toBe(3);
		});
	});

	describe('roundDiscount', () => {
		// WC: always uses HALF_DOWN (WC_DISCOUNT_ROUNDING_MODE = PHP_ROUND_HALF_DOWN)
		it('always uses HALF_DOWN regardless of tax setting', () => {
			expect(roundDiscount(2.725, 2)).toBe(2.72);
			expect(roundDiscount(0.225, 2)).toBe(0.22);
			expect(roundDiscount(19.275, 2)).toBe(19.27);
		});

		it('rounds non-midpoints normally', () => {
			expect(roundDiscount(2.726, 2)).toBe(2.73);
			expect(roundDiscount(2.724, 2)).toBe(2.72);
		});

		it('rounds to 0 precision', () => {
			expect(roundDiscount(2.5, 0)).toBe(2);
			expect(roundDiscount(2.6, 0)).toBe(3);
		});
	});

	describe('getRoundingPrecision', () => {
		it('returns max(dp + 2, 6)', () => {
			expect(getRoundingPrecision(0)).toBe(6);
			expect(getRoundingPrecision(2)).toBe(6);
			expect(getRoundingPrecision(3)).toBe(6);
			expect(getRoundingPrecision(4)).toBe(6);
			expect(getRoundingPrecision(5)).toBe(7);
			expect(getRoundingPrecision(6)).toBe(8);
		});
	});

	describe('addNumberPrecision', () => {
		// wc_add_number_precision: shifts decimal to "cents"
		it('shifts standard prices to cents', () => {
			expect(addNumberPrecision(9.99, 2)).toBe(999);
			expect(addNumberPrecision(10, 2)).toBe(1000);
			expect(addNumberPrecision(0.5, 2)).toBe(50);
			expect(addNumberPrecision(0.01, 2)).toBe(1);
		});

		it('handles midpoint amounts correctly', () => {
			// 1.005 * 100 = 100.49999... in IEEE754 — must round to 100.5
			expect(addNumberPrecision(1.005, 2)).toBe(100.5);
			// 45.225 * 100 — the midpoint detection matters here
			expect(addNumberPrecision(45.225, 2)).toBe(4522.5);
			expect(addNumberPrecision(19.275, 2)).toBe(1927.5);
		});

		it('handles dp=0 (JPY)', () => {
			expect(addNumberPrecision(100, 0)).toBe(100);
		});

		it('handles dp=3', () => {
			expect(addNumberPrecision(9.999, 3)).toBe(9999);
		});

		it('with round=false uses full rounding precision', () => {
			expect(addNumberPrecision(9.99, 2, false)).toBe(999);
		});
	});

	describe('removeNumberPrecision', () => {
		it('shifts cents back to decimal', () => {
			expect(removeNumberPrecision(999, 2)).toBe(9.99);
			expect(removeNumberPrecision(1000, 2)).toBe(10);
			expect(removeNumberPrecision(100, 0)).toBe(100);
			expect(removeNumberPrecision(9999, 3)).toBe(9.999);
		});
	});
});

/**
 * Regression tests for specific parity bugs discovered during integration testing.
 * Each test documents the exact scenario that failed, the root cause, and the fix.
 */
describe('precision — parity regression tests', () => {
	describe('dev-free: hoodie-with-zipper_pct5 discount_tax', () => {
		// Bug: Hoodie with Zipper ($45, 10% tax excl), 5% coupon
		// discount = 2.25, discount_tax = 2.25 * 10% = 0.225
		// Server: order.discount_tax = 0.23 (from coupon line)
		// Client: subtotal_tax(4.5) - total_tax(4.275) = 0.22499... → was rounding to 0.22
		//
		// Root cause: 4.5 - 4.275 = 0.22499999999999964 in IEEE 754, NOT 0.225.
		// This is a different float than the literal 0.225.
		it('float subtraction 4.5 - 4.275 rounds to 0.22 (not midpoint)', () => {
			expect(roundHalfUp(4.5 - 4.275, 2)).toBe(0.22);
		});

		it('literal 0.225 rounds to 0.23 (is midpoint)', () => {
			expect(roundHalfUp(0.225, 2)).toBe(0.23);
		});
	});

	describe('local: long-sleeve-tee_percent7half discount_total', () => {
		// Bug: Long Sleeve Tee (€25 incl 20% VAT), 7.5% coupon
		// ex-tax total after coupon = 19.275
		// Server: roundedItemTotal = round(19.275, 2) = 19.28 (PHP)
		// Client: was getting 19.27 due to Number.EPSILON approach
		//
		// Root cause: 19.275 * 100 = 1927.4999999999998 in IEEE 754.
		// Number.EPSILON added before multiply was negligible at this magnitude.
		it('19.275 rounds to 19.28 (midpoint at large magnitude)', () => {
			expect(roundHalfUp(19.275, 2)).toBe(19.28);
		});

		it('142.575 rounds to 142.58 (same class of bug)', () => {
			expect(roundHalfUp(142.575, 2)).toBe(142.58);
		});
	});

	describe('dev-free: sale-nosale_cart3 total_tax', () => {
		// Bug: 2 items with per-rate taxes 1.633 and 1.634.
		// Server: rounds each to dp before summing → 1.63 + 1.63 = 3.26
		// Client: was summing unrounded → 3.267, then rounding to 3.27
		//
		// Root cause: when taxRoundAtSubtotal=false, WC rounds per-item per-rate
		// taxes to dp before accumulating into tax_lines.
		it('1.633 rounds to 1.63 (below midpoint)', () => {
			expect(roundTaxTotal(1.633, 2, false)).toBe(1.63);
		});

		it('1.634 rounds to 1.63 (below midpoint)', () => {
			expect(roundTaxTotal(1.634, 2, false)).toBe(1.63);
		});

		it('per-item rounded sum = 3.26, not 3.27', () => {
			const perItem1 = roundTaxTotal(1.633, 2, false);
			const perItem2 = roundTaxTotal(1.634, 2, false);
			expect(perItem1 + perItem2).toBe(3.26);
		});
	});
});
