export interface ThemeProps {
	BUTTON_TEXT_COLOR: string;
	BUTTON_BACKGROUND_COLOR: string;
	BUTTON_BACKGROUND_COLOR_DISABLED: string;
	BUTTONGROUP_BORDER_COLOR: string;
	BUTTONGROUP_TEXT_COLOR: string;

	CHECKBOX_BACKGROUND_COLOR: string;
	CHECKBOX_BACKGROUND_COLOR_DISABLED: string;
	CHECKBOX_BORDER_COLOR: string;
	CHECKBOX_BORDER_RADIUS: string;
	CHECKBOX_BORDER_WIDTH: string;
	CHECKBOX_INFO_COLOR: string;
	CHECKBOX_INFO_FONT_SIZE: number;
	CHECKBOX_LABEL_COLOR: string;
	CHECKBOX_LABEL_FONT_SIZE: number;

	FONT_FAMILY: string;

	FONT_SIZE: number;
	FONT_SIZE_LARGE: number;
	FONT_SIZE_SMALL: number;

	FONT_WEIGHT: number;
	FONT_WEIGHT_BOLD: number;
	FONT_WEIGHT_LIGHT: number;

	INPUT_BACKGROUND_COLOR: string;
	INPUT_BORDER_COLOR: string;
	INPUT_BORDER_RADIUS: string;
	INPUT_BORDER_WIDTH: string;
	INPUT_ERROR_TEXT_COLOR: string;
	INPUT_PADDING: string;
	INPUT_FONT_SIZE: number;
	INPUT_TEXT_COLOR: string;

	LIST_ITEM_PADDING: string;

	LOADER_COLOR: string;

	MASTERBAR_BACKGROUND_COLOR: string;
	MASTERBAR_TITLE_COLOR: string;
	MASTERBAR_TITLE_SIZE: string;

	SEGMENT_BACKGROUND_COLOR: string;
	SEGMENT_BORDER_COLOR: string;
	SEGMENT_BORDER_RADIUS: string;
	SEGMENT_BORDER_WIDTH: string;
	SEGMENT_PADDING: string;
	SEGMENT_MARGIN_BOTTOM: string;

	SEGMENT_GROUP_PADDING: string;

	SIDEBAR_BACKGROUND_COLOR: string;

	TEXT_COLOR: string;
	TEXT_COLOR_SECONDARY: string;
}
