/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * save, and this file will regenerate automatically.
 */

/**
 * WooCommerce Product schema
 */
export interface WooCommerceProductSchema {
  id?: string;
  name?: string;
  slug?: string;
  type?: "simple" | "grouped" | "external" | "variable";
  sku?: string;
  regular_price?: string;
  sale_price?: string;
  [k: string]: any;
}
