import { sessionOutboxProperties } from './register-sessions';

const money = { type: 'string' } as const;
const tenders = { type: 'object', additionalProperties: money } as const;
export const closuresLiteral = {
	title: 'Register closures',
	version: 0,
	type: 'object',
	primaryKey: 'id',
	properties: {
		id: { type: 'string', maxLength: 36 },
		session_id: { type: 'string', maxLength: 36 },
		register_id: { type: 'string', maxLength: 36 },
		store_id: { type: ['number', 'null'] },
		number: { type: 'number' },
		opened_at: { type: 'string' },
		closed_at: { type: 'string' },
		till_expected: tenders,
		expected: tenders,
		counted: tenders,
		variance: tenders,
		period_sales_total: money,
		period_refunds_total: money,
		perpetual_sales_total: money,
		perpetual_refunds_total: money,
		unsynced_count: { type: 'number' },
		unsynced_total: money,
		first_sale_counter: { type: ['number', 'null'] },
		last_sale_counter: { type: ['number', 'null'] },
		software_version: { type: 'string' },
		breakdowns: { type: 'object', additionalProperties: true },
		order_ids: { type: 'array', items: { type: 'string' } },
		movement_ids: { type: 'array', items: { type: 'string' } },
		server_number: { type: ['number', 'null'], default: null },
		printed_number: { type: ['number', 'null'], default: null },
		server_findings: { type: ['object', 'null'], additionalProperties: true, default: null },
		server_closure_id: { type: ['string', 'null'], default: null },
		synced_rows_at: { type: ['string', 'null'], default: null },
		printed_at: { type: ['string', 'null'], default: null },
		print_count: { type: 'number', default: 0 },
		number_retried: { type: 'boolean', default: false },
		...sessionOutboxProperties,
		sync_status: {
			type: 'string',
			enum: ['pending', 'synced', 'failed', 'superseded'],
			maxLength: 10,
		},
	},
	required: [
		'id',
		'session_id',
		'register_id',
		'number',
		'opened_at',
		'closed_at',
		'till_expected',
		'expected',
		'counted',
		'variance',
		'period_sales_total',
		'period_refunds_total',
		'perpetual_sales_total',
		'perpetual_refunds_total',
		'unsynced_count',
		'unsynced_total',
		'software_version',
		'breakdowns',
		'order_ids',
		'movement_ids',
		'sync_status',
		'sync_attempts',
		'print_count',
	],
	indexes: [['register_id'], ['session_id'], ['sync_status']],
} as const;
