// NOTE: This file is generated by uniwind and it should not be edited manually.
/// <reference types="uniwind/types" />

import 'react-native';

declare module 'uniwind' {
    export interface UniwindConfig {
        themes: readonly ['light', 'dark', 'ocean', 'sunset', 'monochrome']
    }
}

declare module 'react-native' {
	interface ViewProps {
		className?: string;
	}

	interface TextProps {
		className?: string;
	}

	interface PressableProps {
		className?: string;
	}
}

export {}
