import type { ReceiptData } from '../types';

export const sampleReceiptData: ReceiptData = {
  meta: {
    schema_version: 1,
    mode: 'live',
    created_at_gmt: '2026-03-06 14:30:00',
    order_id: 123,
    order_number: '1042',
    currency: 'USD',
  },
  store: {
    name: 'My Test Store',
    address_lines: ['123 Main Street', 'Suite 100'],
    phone: '(555) 123-4567',
    tax_id: 'TAX-12345',
  },
  cashier: { id: 1, name: 'Jane' },
  customer: { id: 2, name: 'John Doe' },
  lines: [
    {
      key: 'item-1',
      sku: 'SKU-001',
      name: 'Widget A',
      qty: 2,
      unit_price_incl: 5.0,
      unit_price_excl: 4.55,
      line_subtotal_incl: 10.0,
      line_subtotal_excl: 9.09,
      discounts_incl: 0,
      discounts_excl: 0,
      line_total_incl: 10.0,
      line_total_excl: 9.09,
      taxes: [],
    },
    {
      key: 'item-2',
      sku: 'SKU-002',
      name: 'Gadget B',
      qty: 1,
      unit_price_incl: 15.0,
      unit_price_excl: 13.64,
      line_subtotal_incl: 15.0,
      line_subtotal_excl: 13.64,
      discounts_incl: 0,
      discounts_excl: 0,
      line_total_incl: 15.0,
      line_total_excl: 13.64,
      taxes: [],
    },
  ],
  fees: [],
  shipping: [],
  discounts: [],
  totals: {
    subtotal_incl: 25.0,
    subtotal_excl: 22.73,
    discount_total_incl: 0,
    discount_total_excl: 0,
    tax_total: 2.27,
    grand_total_incl: 25.0,
    grand_total_excl: 22.73,
    paid_total: 25.0,
    change_total: 0,
  },
  tax_summary: [
    {
      code: 'US-CA-TAX-1',
      rate: 10,
      label: 'Tax',
      taxable_amount_excl: 22.73,
      tax_amount: 2.27,
      taxable_amount_incl: 25.0,
    },
  ],
  payments: [
    {
      method_id: 'pos_cash',
      method_title: 'Cash',
      amount: 25.0,
      tendered: 30.0,
      change: 5.0,
    },
  ],
  fiscal: {},
  presentation_hints: {
    display_tax: 'incl',
    prices_entered_with_tax: true,
    rounding_mode: 'round',
    locale: 'en-US',
  },
};
