import type { ReceiptData } from '../types';

const emptyDate = {
	datetime: '',
	date: '',
	time: '',
	datetime_short: '',
	datetime_long: '',
	datetime_full: '',
	date_short: '',
	date_long: '',
	date_full: '',
	date_ymd: '',
	date_dmy: '',
	date_mdy: '',
	weekday_short: '',
	weekday_long: '',
	day: '',
	month: '',
	month_short: '',
	month_long: '',
	year: '',
};

export const sampleReceiptData: ReceiptData = {
	order: {
		id: 123,
		number: '1042',
		currency: 'USD',
		customer_note: '',
		needs_payment: false,
		payment_url: 'https://example.test/checkout/order-pay/1042',
		created: { ...emptyDate, datetime: '2026-03-06 14:30:00' },
		paid: emptyDate,
		completed: emptyDate,
		printed: { ...emptyDate, datetime: '2026-03-06 14:35:00' },
	},
	store: {
		id: 1,
		name: 'My Test Store',
		address_lines: ['123 Main Street', 'Suite 100'],
		phone: '(555) 123-4567',
		tax_ids: [{ type: 'other', value: 'TAX-12345' }],
	},
	cashier: { id: 1, name: 'Jane' },
	customer: { id: 2, name: 'John Doe' },
	lines: [
		{
			key: 'item-1',
			sku: 'SKU-001',
			name: 'Widget A',
			qty: 2,
			regular_price: 5,
			regular_price_incl: 5,
			regular_price_excl: 4.545,
			selling_price: 5,
			selling_price_incl: 5,
			selling_price_excl: 4.545,
			unit_savings: 0,
			unit_savings_incl: 0,
			unit_savings_excl: 0,
			line_regular_total: 10,
			line_regular_total_incl: 10,
			line_regular_total_excl: 9.09,
			line_selling_total: 10,
			line_selling_total_incl: 10,
			line_selling_total_excl: 9.09,
			line_savings: 0,
			line_savings_incl: 0,
			line_savings_excl: 0,
			savings_in_discounts: false,
			unit_price: 5.0,
			unit_price_incl: 5.0,
			unit_price_excl: 4.55,
			line_subtotal: 10.0,
			line_subtotal_incl: 10.0,
			line_subtotal_excl: 9.09,
			discounts: 0,
			discounts_incl: 0,
			discounts_excl: 0,
			line_total: 10.0,
			line_total_incl: 10.0,
			line_total_excl: 9.09,
			meta: [],
			taxes: [],
		},
		{
			key: 'item-2',
			sku: 'SKU-002',
			name: 'Gadget B',
			qty: 1,
			regular_price: 15,
			regular_price_incl: 15,
			regular_price_excl: 13.64,
			selling_price: 15,
			selling_price_incl: 15,
			selling_price_excl: 13.64,
			unit_savings: 0,
			unit_savings_incl: 0,
			unit_savings_excl: 0,
			line_regular_total: 15,
			line_regular_total_incl: 15,
			line_regular_total_excl: 13.64,
			line_selling_total: 15,
			line_selling_total_incl: 15,
			line_selling_total_excl: 13.64,
			line_savings: 0,
			line_savings_incl: 0,
			line_savings_excl: 0,
			savings_in_discounts: false,
			unit_price: 15.0,
			unit_price_incl: 15.0,
			unit_price_excl: 13.64,
			line_subtotal: 15.0,
			line_subtotal_incl: 15.0,
			line_subtotal_excl: 13.64,
			discounts: 0,
			discounts_incl: 0,
			discounts_excl: 0,
			line_total: 15.0,
			line_total_incl: 15.0,
			line_total_excl: 13.64,
			meta: [],
			taxes: [],
		},
	],
	fees: [],
	shipping: [],
	discounts: [],
	totals: {
		subtotal: 25.0,
		subtotal_incl: 25.0,
		subtotal_excl: 22.73,
		discount_total: 0,
		discount_total_incl: 0,
		discount_total_excl: 0,
		sale_savings_total: 0,
		sale_savings_total_incl: 0,
		sale_savings_total_excl: 0,
		total_saved: 0,
		total_saved_incl: 0,
		total_saved_excl: 0,
		total_saved_complete: true,
		tax_total: 2.27,
		total: 25.0,
		total_incl: 25.0,
		total_excl: 22.73,
		paid_total: 25.0,
		change_total: 0,
		total_qty: 3,
		line_count: 2,
	},
	tax_summary: [
		{
			code: 'US-CA-TAX-1',
			rate: 10,
			label: 'Tax',
			taxable_amount_excl: 22.73,
			tax_amount: 2.27,
			taxable_amount_incl: 25.0,
		},
	],
	payments: [
		{
			method_id: 'pos_cash',
			method_title: 'Cash',
			amount: 25.0,
			tendered: 30.0,
			change: 5.0,
		},
	],
	fiscal: {},
	presentation_hints: {
		display_tax: 'incl',
		prices_entered_with_tax: true,
		rounding_mode: 'round',
		locale: 'en-US',
	},
};
