/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * save, and this file will regenerate automatically.
 */

/**
 * WooCommerce Payment Gateway schema
 */
export interface WooCommercePaymentGatewaySchema {
  /**
   * Unique local identifier for the resource.
   */
  _id?: string;
  id?: string;
  description?: string;
  order?: number;
  enabled?: boolean;
  method_title?: string;
  method_description?: string;
  method_supports?: string[];
  [k: string]: any;
}
