/**
 * Mock for @wcpos/utils/logger/error-codes
 */

module.exports = {
	ERROR_CODES: {
		INVALID_DATA_TYPE: 'INVALID_DATA_TYPE',
		NETWORK_ERROR: 'NETWORK_ERROR',
		AUTH_ERROR: 'AUTH_ERROR',
		NOT_FOUND: 'NOT_FOUND',
		PARSE_ERROR: 'PARSE_ERROR',
		VALIDATION_ERROR: 'VALIDATION_ERROR',
		CONNECTION_ERROR: 'CONNECTION_ERROR',
		TIMEOUT_ERROR: 'TIMEOUT_ERROR',
		UNKNOWN_ERROR: 'UNKNOWN_ERROR',
	},
};
