/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * save, and this file will regenerate automatically.
 */

/**
 * WooCommerce Product Tag schema
 */
export interface WooCommerceProductTagSchema {
  /**
   * Unique identifier for the resource.
   */
  uuid?: string;
  /**
   * Unique remote identifier for the resource.
   */
  id?: number;
  /**
   * Tag name.
   */
  name?: string;
  /**
   * An alphanumeric identifier for the resource unique to its type.
   */
  slug?: string;
  /**
   * Number of published products for the resource.
   */
  count?: number;
  links?: {
    collection?: {
      href?: string;
      [k: string]: any;
    }[];
    self?: {
      href?: string;
      [k: string]: any;
    }[];
    [k: string]: any;
  };
  [k: string]: any;
}
