/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * save, and this file will regenerate automatically.
 */

/**
 * WordPress User credientials
 */
export interface WordPressUserSchema {
  id?: string;
  remote_id?: number;
  username?: string;
  first_name?: string;
  last_name?: string;
  email?: string;
  display_name?: string;
  last_access?: string;
  consumer_key?: string;
  consumer_secret?: string;
  key_id?: number;
  key_permissions?: string;
  [k: string]: any;
}
