/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * save, and this file will regenerate automatically.
 */

/**
 * WooCommerce Product schema
 */
export interface WooCommerceProductSchema {
  id?: number;
  name?: string;
  slug?: string;
  permalink?: string;
  dateCreated?: string;
  dateCreatedGmt?: string;
  dateModified?: string;
  dateModifiedGmt?: string;
  type?: "simple" | "grouped" | "external" | "variable";
  status?: "draft" | "pending" | "private" | "publish";
  featured?: boolean;
  catalogVisibility?: string;
  description?: string;
  shortDescription?: string;
  sku?: string;
  price?: string;
  regularPrice?: string;
  salePrice?: string;
  dateOnSaleFrom?: string | null;
  dateOnSaleFromGmt?: string | null;
  dateOnSaleTo?: string | null;
  dateOnSaleToGmt?: string | null;
  priceHtml?: string;
  onSale?: boolean;
  purchasable?: boolean;
  totalSales?: number;
  virtual?: boolean;
  downloadable?: boolean;
  downloads?: any[];
  downloadLimit?: number;
  downloadExpiry?: number;
  externalUrl?: string;
  buttonText?: string;
  taxStatus?: "taxable" | "shipping" | "none";
  taxClass?: string;
  manageStock?: boolean;
  stockQuantity?: number | null;
  stockStatus?: "instock" | "outofstock" | "onbackorder";
  backorders?: "no" | "notify" | "yes";
  backordersAllowed?: boolean;
  backordered?: boolean;
  soldIndividually?: boolean;
  weight?: string;
  dimensions?: {
    length?: string;
    width?: string;
    height?: string;
    [k: string]: any;
  };
  shippingRequired?: boolean;
  shippingTaxable?: boolean;
  shippingClass?: string;
  shippingClassId?: number;
  reviewsAllowed?: boolean;
  averageRating?: string;
  ratingCount?: number;
  relatedIds?: number[];
  upsellIds?: number[];
  crossSellIds?: number[];
  parentId?: number;
  purchaseNote?: string;
  categories?: {
    id?: number;
    name?: string;
    slug?: string;
    [k: string]: any;
  }[];
  tags?: {
    id?: number;
    name?: string;
    slug?: string;
    [k: string]: any;
  }[];
  images?: {
    id?: number;
    dateCreated?: string;
    dateCreatedGmt?: string;
    dateModified?: string;
    dateModifiedGmt?: string;
    src?: string;
    name?: string;
    alt?: string;
    [k: string]: any;
  }[];
  attributes?: {
    id?: number;
    name?: string;
    position?: number;
    visible?: boolean;
    variation?: boolean;
    options?: string[];
    [k: string]: any;
  }[];
  defaultAttributes?: {
    id?: number;
    name?: string;
    option?: string;
    [k: string]: any;
  }[];
  variations?: number[];
  groupedProducts?: number[];
  menuOrder?: number;
  metaData?: {
    id?: number;
    key?: string;
    value?: string;
    [k: string]: any;
  }[];
  links?: {
    collection?: {
      href?: string;
      [k: string]: any;
    }[];
    self?: {
      href?: string;
      [k: string]: any;
    }[];
    [k: string]: any;
  };
  thumbnail?: string;
  [k: string]: any;
}
