/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * save, and this file will regenerate automatically.
 */

/**
 * Logs events for debugging and user record
 */
export interface LogSchema {
  /**
   * Unique identifier for the resource.
   */
  uuid?: string;
  dateCreatedGmt?: string;
  user?: string;
  level?: string;
  message?: string;
  meta?: {
    [k: string]: any;
  };
  [k: string]: any;
}
