name: Run Tests

on:
  push:
    branches:
      - "**"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3.6.0
        with:
          node-version: 16.x
      - run: npm install --force

      - name: Run tests
        run: npm test
