/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * save, and this file will regenerate automatically.
 */

/**
 * WooCommerce Order schema
 */
export interface WooCommerceOrderSchema {
  id?: number;
  /**
   * Parent order ID.
   */
  parentId?: number;
  number?: string;
  orderKey?: string;
  createdVia?: string;
  version?: string;
  /**
   * Order status.
   */
  status?: "pending" | "processing" | "on-hold" | "completed" | "cancelled" | "refunded" | "failed";
  /**
   * Currency the order was created with, in ISO format.
   */
  currency?:
    | "AED"
    | "AFN"
    | "ALL"
    | "AMD"
    | "ANG"
    | "AOA"
    | "ARS"
    | "AUD"
    | "AWG"
    | "AZN"
    | "BAM"
    | "BBD"
    | "BDT"
    | "BGN"
    | "BHD"
    | "BIF"
    | "BMD"
    | "BND"
    | "BOB"
    | "BRL"
    | "BSD"
    | "BTC"
    | "BTN"
    | "BWP"
    | "BYR"
    | "BYN"
    | "BZD"
    | "CAD"
    | "CDF"
    | "CHF"
    | "CLP"
    | "CNY"
    | "COP"
    | "CRC"
    | "CUC"
    | "CUP"
    | "CVE"
    | "CZK"
    | "DJF"
    | "DKK"
    | "DOP"
    | "DZD"
    | "EGP"
    | "ERN"
    | "ETB"
    | "EUR"
    | "FJD"
    | "FKP"
    | "GBP"
    | "GEL"
    | "GGP"
    | "GHS"
    | "GIP"
    | "GMD"
    | "GNF"
    | "GTQ"
    | "GYD"
    | "HKD"
    | "HNL"
    | "HRK"
    | "HTG"
    | "HUF"
    | "IDR"
    | "ILS"
    | "IMP"
    | "INR"
    | "IQD"
    | "IRR"
    | "IRT"
    | "ISK"
    | "JEP"
    | "JMD"
    | "JOD"
    | "JPY"
    | "KES"
    | "KGS"
    | "KHR"
    | "KMF"
    | "KPW"
    | "KRW"
    | "KWD"
    | "KYD"
    | "KZT"
    | "LAK"
    | "LBP"
    | "LKR"
    | "LRD"
    | "LSL"
    | "LYD"
    | "MAD"
    | "MDL"
    | "MGA"
    | "MKD"
    | "MMK"
    | "MNT"
    | "MOP"
    | "MRU"
    | "MUR"
    | "MVR"
    | "MWK"
    | "MXN"
    | "MYR"
    | "MZN"
    | "NAD"
    | "NGN"
    | "NIO"
    | "NOK"
    | "NPR"
    | "NZD"
    | "OMR"
    | "PAB"
    | "PEN"
    | "PGK"
    | "PHP"
    | "PKR"
    | "PLN"
    | "PRB"
    | "PYG"
    | "QAR"
    | "RON"
    | "RSD"
    | "RUB"
    | "RWF"
    | "SAR"
    | "SBD"
    | "SCR"
    | "SDG"
    | "SEK"
    | "SGD"
    | "SHP"
    | "SLL"
    | "SOS"
    | "SRD"
    | "SSP"
    | "STN"
    | "SYP"
    | "SZL"
    | "THB"
    | "TJS"
    | "TMT"
    | "TND"
    | "TOP"
    | "TRY"
    | "TTD"
    | "TWD"
    | "TZS"
    | "UAH"
    | "UGX"
    | "USD"
    | "UYU"
    | "UZS"
    | "VEF"
    | "VES"
    | "VND"
    | "VUV"
    | "WST"
    | "XAF"
    | "XCD"
    | "XOF"
    | "XPF"
    | "YER"
    | "ZAR"
    | "ZMW";
  dateCreated?: string;
  dateCreatedGmt?: string;
  dateModified?: string;
  dateModifiedGmt?: string;
  discountTotal?: string;
  discountTax?: string;
  shippingTotal?: string;
  shippingTax?: string;
  cartTax?: string;
  total?: string;
  totalTax?: string;
  pricesIncludeTax?: boolean;
  /**
   * User ID who owns the order. 0 for guests.
   */
  customerId?: number;
  customerIpAddress?: string;
  customerUserAgent?: string;
  /**
   * Note left by customer during checkout.
   */
  customerNote?: string;
  /**
   * Billing address.
   */
  billing?: {
    [k: string]: any;
  };
  /**
   * Shipping address.
   */
  shipping?: {
    [k: string]: any;
  };
  /**
   * Payment method ID.
   */
  paymentMethod?: string;
  /**
   * Payment method title.
   */
  paymentMethodTitle?: string;
  /**
   * Unique transaction ID.
   */
  transactionId?: string;
  datePaid?: string | null;
  datePaidGmt?: string | null;
  dateCompleted?: string | null;
  dateCompletedGmt?: string | null;
  cartHash?: string;
  /**
   * Meta data.
   */
  metaData?: {
    /**
     * Meta ID.
     */
    id?: number;
    /**
     * Meta key.
     */
    key?: string;
    /**
     * Meta value.
     */
    value?: string;
    [k: string]: any;
  }[];
  /**
   * Line items data.
   */
  lineItems?: string[];
  taxLines?: {
    id?: number;
    rateCode?: string;
    rateId?: number;
    label?: string;
    compound?: boolean;
    taxTotal?: string;
    shippingTaxTotal?: string;
    ratePercent?: number;
    /**
     * Meta data.
     */
    metaData?: {
      /**
       * Meta ID.
       */
      id?: number;
      /**
       * Meta key.
       */
      key?: string;
      /**
       * Meta value.
       */
      value?: string;
      [k: string]: any;
    }[];
    [k: string]: any;
  }[];
  /**
   * Shipping lines data.
   */
  shippingLines?: string[];
  /**
   * Fee lines data.
   */
  feeLines?: string[];
  /**
   * Coupons line data.
   */
  couponLines?: {
    /**
     * Item ID.
     */
    id?: number;
    /**
     * Coupon code.
     */
    code?: string;
    /**
     * Discount total.
     */
    discount?: string;
    /**
     * Discount total tax.
     */
    discountTax?: string;
    /**
     * Meta data.
     */
    metaData?: {
      /**
       * Meta ID.
       */
      id?: number;
      /**
       * Meta key.
       */
      key?: string;
      /**
       * Meta value.
       */
      value?: string;
      [k: string]: any;
    }[];
    [k: string]: any;
  }[];
  refunds?: {
    id?: number;
    reason?: string;
    total?: string;
    [k: string]: any;
  }[];
  currencySymbol?: string;
  [k: string]: any;
}
